// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: embeddings.proto

package embeddingspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenIds      []int64                `protobuf:"varint,1,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingsRequest) Reset() {
	*x = EmbeddingsRequest{}
	mi := &file_embeddings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingsRequest) ProtoMessage() {}

func (x *EmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embeddings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_embeddings_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingsRequest) GetTokenIds() []int64 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

type EmbeddingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Optional error message if success is false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingsResponse) Reset() {
	*x = EmbeddingsResponse{}
	mi := &file_embeddings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingsResponse) ProtoMessage() {}

func (x *EmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embeddings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_embeddings_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmbeddingsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_embeddings_proto protoreflect.FileDescriptor

const file_embeddings_proto_rawDesc = "" +
	"\n" +
	"\x10embeddings.proto\x12\n" +
	"embeddings\"0\n" +
	"\x11EmbeddingsRequest\x12\x1b\n" +
	"\ttoken_ids\x18\x01 \x03(\x03R\btokenIds\"S\n" +
	"\x12EmbeddingsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2a\n" +
	"\n" +
	"Embeddings\x12S\n" +
	"\x12GenerateEmbeddings\x12\x1d.embeddings.EmbeddingsRequest\x1a\x1e.embeddings.EmbeddingsResponseB\x10Z\x0e./embeddingspbb\x06proto3"

var (
	file_embeddings_proto_rawDescOnce sync.Once
	file_embeddings_proto_rawDescData []byte
)

func file_embeddings_proto_rawDescGZIP() []byte {
	file_embeddings_proto_rawDescOnce.Do(func() {
		file_embeddings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embeddings_proto_rawDesc), len(file_embeddings_proto_rawDesc)))
	})
	return file_embeddings_proto_rawDescData
}

var file_embeddings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_embeddings_proto_goTypes = []any{
	(*EmbeddingsRequest)(nil),  // 0: embeddings.EmbeddingsRequest
	(*EmbeddingsResponse)(nil), // 1: embeddings.EmbeddingsResponse
}
var file_embeddings_proto_depIdxs = []int32{
	0, // 0: embeddings.Embeddings.GenerateEmbeddings:input_type -> embeddings.EmbeddingsRequest
	1, // 1: embeddings.Embeddings.GenerateEmbeddings:output_type -> embeddings.EmbeddingsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_embeddings_proto_init() }
func file_embeddings_proto_init() {
	if File_embeddings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embeddings_proto_rawDesc), len(file_embeddings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embeddings_proto_goTypes,
		DependencyIndexes: file_embeddings_proto_depIdxs,
		MessageInfos:      file_embeddings_proto_msgTypes,
	}.Build()
	File_embeddings_proto = out.File
	file_embeddings_proto_goTypes = nil
	file_embeddings_proto_depIdxs = nil
}
