# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embeddings.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'embeddings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65mbeddings.proto\x12\nembeddings\"B\n\x11\x45mbeddingsRequest\x12\x11\n\ttoken_ids\x18\x01 \x03(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\"<\n\x12\x45mbeddingsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"6\n\x12\x46indSimilarRequest\x12\x11\n\ttoken_ids\x18\x01 \x03(\x03\x12\r\n\x05top_k\x18\x02 \x01(\x05\"T\n\x13\x46indSimilarResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rsimilar_texts\x18\x02 \x03(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xbb\x01\n\nEmbeddings\x12S\n\x12GenerateEmbeddings\x12\x1d.embeddings.EmbeddingsRequest\x1a\x1e.embeddings.EmbeddingsResponse\x12X\n\x15\x46indSimilarEmbeddings\x12\x1e.embeddings.FindSimilarRequest\x1a\x1f.embeddings.FindSimilarResponseB\x10Z\x0e./embeddingspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016./embeddingspb'
  _globals['_EMBEDDINGSREQUEST']._serialized_start=32
  _globals['_EMBEDDINGSREQUEST']._serialized_end=98
  _globals['_EMBEDDINGSRESPONSE']._serialized_start=100
  _globals['_EMBEDDINGSRESPONSE']._serialized_end=160
  _globals['_FINDSIMILARREQUEST']._serialized_start=162
  _globals['_FINDSIMILARREQUEST']._serialized_end=216
  _globals['_FINDSIMILARRESPONSE']._serialized_start=218
  _globals['_FINDSIMILARRESPONSE']._serialized_end=302
  _globals['_EMBEDDINGS']._serialized_start=305
  _globals['_EMBEDDINGS']._serialized_end=492
# @@protoc_insertion_point(module_scope)
