# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tokenizer.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'tokenizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftokenizer.proto\x12\ttokenizer\"\x1d\n\rEncodeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"5\n\x0e\x45ncodeResponse\x12\x0e\n\x06tokens\x18\x01 \x03(\x03\x12\x13\n\x0btoken_texts\x18\x02 \x03(\t2J\n\tTokenizer\x12=\n\x06\x45ncode\x12\x18.tokenizer.EncodeRequest\x1a\x19.tokenizer.EncodeResponseB\x0fZ\r./tokenizerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./tokenizerpb'
  _globals['_ENCODEREQUEST']._serialized_start=30
  _globals['_ENCODEREQUEST']._serialized_end=59
  _globals['_ENCODERESPONSE']._serialized_start=61
  _globals['_ENCODERESPONSE']._serialized_end=114
  _globals['_TOKENIZER']._serialized_start=116
  _globals['_TOKENIZER']._serialized_end=190
# @@protoc_insertion_point(module_scope)
