// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: tokenizer.proto

package tokenizerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tokenizer_Encode_FullMethodName = "/tokenizer.Tokenizer/Encode"
)

// TokenizerClient is the client API for Tokenizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenizerClient interface {
	Encode(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error)
}

type tokenizerClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenizerClient(cc grpc.ClientConnInterface) TokenizerClient {
	return &tokenizerClient{cc}
}

func (c *tokenizerClient) Encode(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeResponse)
	err := c.cc.Invoke(ctx, Tokenizer_Encode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenizerServer is the server API for Tokenizer service.
// All implementations must embed UnimplementedTokenizerServer
// for forward compatibility.
type TokenizerServer interface {
	Encode(context.Context, *EncodeRequest) (*EncodeResponse, error)
	mustEmbedUnimplementedTokenizerServer()
}

// UnimplementedTokenizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenizerServer struct{}

func (UnimplementedTokenizerServer) Encode(context.Context, *EncodeRequest) (*EncodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encode not implemented")
}
func (UnimplementedTokenizerServer) mustEmbedUnimplementedTokenizerServer() {}
func (UnimplementedTokenizerServer) testEmbeddedByValue()                   {}

// UnsafeTokenizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenizerServer will
// result in compilation errors.
type UnsafeTokenizerServer interface {
	mustEmbedUnimplementedTokenizerServer()
}

func RegisterTokenizerServer(s grpc.ServiceRegistrar, srv TokenizerServer) {
	// If the following call pancis, it indicates UnimplementedTokenizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tokenizer_ServiceDesc, srv)
}

func _Tokenizer_Encode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizerServer).Encode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokenizer_Encode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizerServer).Encode(ctx, req.(*EncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tokenizer_ServiceDesc is the grpc.ServiceDesc for Tokenizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tokenizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenizer.Tokenizer",
	HandlerType: (*TokenizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encode",
			Handler:    _Tokenizer_Encode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tokenizer.proto",
}
